# .yml file for CI/CD pipeline

# Define the pipeline stages
name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger the pipeline on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2  # Action to check out your repository's code

      - name: Install dependencies and build
        run: |
          yarn install  # Install project dependencies
          yarn build    # Build the React app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Use Node.js 16

      - name: Build and run Docker container
        run: |
          docker build -t todo-app .  # Build the Docker image
          docker run -d -p 5173:5173 todo-app  # Run the Docker container
