# .github/workflows/main.yml

name: Deploy React App to AWS EBS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-north-1
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name Docker-React --version-label 1234 --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-401735561383,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --environment-name Docker-React-env --version-label 1234
      

      
